FROM gradle:8 AS base
CMD ["bash"]

# test-and-build
FROM base AS build
COPY . /workspace
WORKDIR /workspace/api
RUN ./gradlew build

# production
FROM openjdk:21 AS production
COPY --from=build /workspace/api/build/libs/api-0.0.1-SNAPSHOT.jar ./api.jar
CMD [ "java", "-jar", "api.jar" ]